import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Sona",
  description: "How Sona handles your family's information.",
};

/**
 * TEMPLATE — not legal advice. Before launch, fill in the bracketed details and
 * have this reviewed by a lawyer familiar with COPPA and your jurisdiction.
 * A kids' product with payments and audio processing has real obligations.
 */
const COMPANY = "Sona (beta)"; // TODO: replace with the legal entity name before wide launch
const SUPPORT_EMAIL = "wardroptravis@gmail.com";
const EFFECTIVE = "June 2026";

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-12 text-[#1f2937]">
      <h1 className="text-3xl font-extrabold text-[#0e9add]">Privacy Policy</h1>
      <p className="mt-1 text-sm text-[#6b7280]">Effective {EFFECTIVE}</p>

      <p className="mt-6 leading-relaxed">
        Sona is an at-home speech practice service for children, designed with a
        licensed speech-language pathologist and operated by {COMPANY}. We built
        it to collect as little as possible and to be safe for kids. This policy
        explains what we collect, why, and the choices you have. A parent or
        guardian sets up and manages every account.
      </p>

      <Section title="Information you give us">
        To create and manage a subscription we collect a <strong>parent&apos;s
        email address</strong> and payment details (handled by Stripe — we never
        see or store card numbers). The child&apos;s <strong>first name or
        nickname, practice plan, progress, and coins</strong> are stored{" "}
        <strong>on your own device</strong> (in the browser), not on our servers
        — Sona has no account database during the beta. Please use a first name
        or nickname only.
      </Section>

      <Section title="Microphone, camera &amp; voice">
        Sessions are <strong>audio only — the camera is never used</strong>, and
        the microphone is only active while your child is practicing. When cloud
        scoring is enabled (you can turn it off in Settings), short clips of your
        child&apos;s attempts are sent to our scoring provider to rate
        pronunciation; we don&apos;t keep them on our servers. Practice
        recordings are also saved <strong>only on your device</strong> so you can
        replay your child&apos;s first try next to their latest in the Progress
        page — they never leave your device, and clearing the app&apos;s data
        deletes them.
      </Section>

      <Section title="The live coach">
        Leo is an animated cartoon character. His words are generated by an AI
        model from the practice context, then spoken with a synthetic voice. In
        the &ldquo;Call Leo&rdquo; chat, what your child says (as recognized
        text, plus their first name and target sound) is sent to the AI provider
        so Leo can reply, with strict child-safety instructions; conversations
        are not used to build profiles.
      </Section>

      <Section title="Service providers">
        We use a small set of vendors strictly to operate Sona. They process data
        only to provide their part of the service:
        <ul className="mt-2 list-disc space-y-1 pl-6">
          <li><strong>Stripe</strong> — subscription billing and payment processing.</li>
          <li><strong>Anthropic (Claude)</strong> — generates the coach&apos;s spoken lines from the practice context.</li>
          <li><strong>ElevenLabs</strong> — text-to-speech for Leo&apos;s voice.</li>
          <li><strong>Speechace</strong> — scores pronunciation from practice audio (when cloud scoring is on).</li>
          <li><strong>Vercel</strong> — hosting and delivery.</li>
        </ul>
      </Section>

      <Section title="Children's privacy (COPPA)">
        Sona is intended to be set up and controlled by a parent or guardian. We
        do not knowingly collect personal information directly from children, we
        show <strong>no third-party advertising</strong>, and there are{" "}
        <strong>no social or chat features</strong> between users. We use
        children&apos;s information only to provide the practice experience and
        the parent&apos;s progress view — never to build advertising profiles. A
        parent can review or delete their family&apos;s data at any time (see
        &ldquo;Your choices&rdquo;). If you believe a child has provided us
        information without parental consent, contact us and we will delete it.
      </Section>

      <Section title="No ads, no selling data">
        Sona contains no third-party advertising and no cross-app tracking, and we
        do not sell or rent your family&apos;s information.
      </Section>

      <Section title="Data retention">
        Progress and recordings live on your device — delete them anytime with
        Settings → Reset, or by clearing the app&apos;s browser data. Billing
        records are kept by Stripe as required. We don&apos;t retain your
        child&apos;s audio on our servers.
      </Section>

      <Section title="Your choices">
        You can update or cancel your subscription, ask us to export or delete
        your family&apos;s data, and disable the microphone in your browser or
        device settings (sessions need the microphone to work). To request
        access or deletion, email us below.
      </Section>

      <Section title="Contact">
        Questions, or a data request? Email{" "}
        <a className="text-[#0e9add] underline" href={`mailto:${SUPPORT_EMAIL}`}>
          {SUPPORT_EMAIL}
        </a>
        .
      </Section>

      <p className="mt-10 text-xs text-[#9ca3af]">
        Sona supports speech practice and is not a medical device, diagnosis, or
        a substitute for professional speech-language services. This document is
        a template and not legal advice; please have it reviewed before launch.
      </p>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-7">
      <h2 className="text-lg font-extrabold text-[#1f2937]">{title}</h2>
      <div className="mt-2 leading-relaxed">{children}</div>
    </section>
  );
}
